language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x ./gradlew
script:
- "./gradlew --no-daemon check --info"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload --debug"
  on:
    tags: true
env:
  global:
  - secure: KqTtbpREtk2jAFE2SNTHUOPfI17tbHKloytAzzxLPqXHMp18u8FXEG7tj7eIn4RpNzfFtir6AVwZ3jMaBYdn9ObYRN4Hys78vYzf4png9xY98taMBM8BbD3pmf3YTb4NfqXw2eo3bjbi0fcLkXCB1aNvBhQE1+o3YMTztmMZthD4el3xhyYXy8npCZF3jSzPpDa4Xev3uUVFq7CnA6ubxt0bnRfKXw9dECi6ZbmPQ65PUowmhuMxxGjsHiFktPUdmU0yC3Ll1JRHaidsQQFjsxCpjLYmXY0c77qr6+qovjD1m1sg7GxwjcBLXwZk9rwbFNYl1dAwiefyEaJn6C327U0dlkIAdz29UstmwpihzGojalXm+6QQfksE/9LExDam3BYhyiIxabVs/Z51Cu5026ur7ACfhgyk7xazkhTW2PypYw6OmqlrW898arRdyHSllah+0cdIGaebK9JqEjSTDLF/L6G0Yzl4Fpx6K24rpYTKdPG+EHuIFs/poTncD5wkx57Cwh5UnDvjcx/kH06AljqGaAQ+jviCaYvfmaKXbVxXm8K7npWo8w+Uvcx+P3KmHBfxjpJpldX/irQ2wsqwcUG8W7BSq8DdKO2Cb8ZDH8/k5Ki5n+Am/1FCoyYmfEuMTgD+HZqgRscCi6hUDTgOQj2lOoA/ToYNsaW6QJjqxsI=
  - secure: k6E0DmAIvuQnSxe9SIrwnVSk4YYT+N3WNqbVQrJK4izlBk/6sYgp0zAenQez4OQRZ9d9alNBml6iEzZdHoRLDQNc39iVwGzCifc7Pvv9oUaLQk6TWovGxMLmCgwTJobPU6izVL4T8so8Wg7d1+Rs+cDZ7W90Zm531u95PnqBempyf77ZJwJ3js/O8laTADga0Gu7mLY9jaXMNV0O66eMiq5oTcSBvKvAdY59UqIoRnbwNPrDIuazRhCPozfMQQNirujsicAejfO6phUKkA0nDW3ywzr8aKIw9zbRYwcSxXGGsNFf2FX2v02mcJv1anTVNgI+B/EdEYwuPE0TiZsWNasbYDGatuDe+D2ZnSumnm2Vjk6extr3sEtTuJwRi88nCrL1AzVv0UUDkP/Wg+5MJkFggqvN6gNOBeuPAPZPl3AsEoIDoQzSRIL5jmsEFfONuVOj6iAFK3iXagXXD+RO0xwMX1UZGGLi+96/TnG9UfQkgXRR9vxZG8roI8So/Z+xRImm/YdyMmSahOce8mPsWR5cMhLfuM+EORCowu3Ie6KACasE7oFO65es6FdHCvTwF3EGdETZTvMd6BRzDw4E3bXCRHcQF252Rp7HdgSpK6Hh8h93wsU0v39iBD0PPGS5m/6jZI4Oi2ONxPG4pOKKqFDWTnAx28DgMzBEpgm/6p4=
